#!/bin/sh
. "$(dirname $0)/_/husky.sh"

# Make sure any changed source is pretty-fied
STAGED=`git diff --name-only --staged`
prettier --write {src,test}/**/*.ts
git add $STAGED

# Make sure docs are current
npm run build
git add docs/
